### ISSUE TITLE
[Enhancement Idea] Autofill

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#11]
I've been testing autofill, and I really like it. Could some improvements be possible? For example in some cases it designates a man with a woman in student parts: Initial Call, Return Visit, etc, it would be necessary to create a filter so that the assistant is someone of the same gender as the student. And another interesting filter would be in the Living as Christians section he would designate the elders parts, just for elders. In this case it would be local needs and the parts where the source material appears as below:

![Screenshot_5](https://user-images.githubusercontent.com/76891864/217678558-52e1e940-8ed3-4ef0-ab48-c5be93a78470.png)

**Comment by rhahao** [comment]
Hi @joaochris, I would like to confirm if you still see the behavior where CPE mixes male and female for a part. Thanks in advance for your feedback.

**Comment by joaochris** [comment]
Hi @rhahao. I can not right now. But he's only picking women. If possible, the ideal was to intersperse the parties between men and women.
And two questions.

1. Is it possible to reduce the time it fills in?

2. Basically what is the logic used for him to choose a certain person?

**Comment by rhahao** [comment]
> But he's only picking women. If possible, the ideal was to intersperse the parts between men and women.

Yes, I could see why it behave like that, but I will try to see on how to adjust this behavior.

> 1. Is it possible to reduce the time it fills in and exclude?

I will look at this too.

> 2. Basically what is the logic used for him to choose a certain person?

Currently, what it does is only checking the last assignment of a person, regardless of which part it is.

**Comment by joaochris** [comment]
> Currently, what it does is only checking the last assignment of a person, regardless of which part it is.

An option that would be very interesting is not to repeat the same brother two weeks in a row (two meetings).

**Comment by rhahao** [comment]
Hi @joaochris, I think these are very nice ideas. I will work on them, and may request your feedback when they are ready.

**Comment by rhahao** [comment]
Hi @joaochris, hope you are doing well. Please note this one should be improved now:
> Is it possible to reduce the time it fills in and exclude?
Thanks!

**Comment by joaochris** [comment]
Hoow everything is faster now! Thanks. I noticed a bug, some words appear in English when assign.
![image](https://user-images.githubusercontent.com/76891864/227934921-54e6098e-130f-4efb-95b0-144ea1f94209.png)

**Comment by rhahao** [comment]
> I noticed a bug, some words appear in English when assign.

This one should be fixed now! Thanks.

**Comment by joaochris** [comment]
Thanks! I run the autofill and noticed that it is repeating several names 😅

**Comment by rhahao** [comment]
Oh... really?? When you open manually the list of those who can be assigned does it display correctly the last assignment date?

**Comment by joaochris** [comment]
Seriously lol. Yes displays.

**Comment by rhahao** [comment]
😁ok thanks for confirming! Just one last question: was your schedule filled consecutively? Currently, the autofill is not able to do the assignment correctly, if you skip months, and then go back to a previous month.

**Comment by joaochris** [comment]
Yes! I filled everything in the sequence :)

**Comment by rhahao** [comment]
Ok, I need to find out why it behaves differently on your side then. I’ve checked with three users here, and we are not able to duplicate the issue.

**Comment by joaochris** [comment]
Hey, I tested it now and it's working. Go figure.😂

**Comment by joaochris** [comment]
@rhahao I edited this too. Actually the first option I suggested from the logic in my tests is not good that it applies to the President, because there are parts that can only be done by elders. So there will be few brothers.

**Comment by joaochris** [comment]
@rhahao I was pretty confused, but now that I've come to understand. Updated this comment https://github.com/sws2apps/cpe-sws/issues/11#issuecomment-1451906061
