### ISSUE TITLE
[FIX] Lookup on assign doesn't work sometimes

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#133]
**To Reproduce**
Fill in several weeks, at some point when searching the name will not appear, even if the person is registered, and even typing the full name.

**Comment by rhahao** [comment]
Thanks for reporting. I will check and verify it.

**Comment by rhahao** [comment]
Does this happen on every assignment, or do you see it on specific assignment only? I’ve tried to duplicate it, but unfortunately, I am not able so fart. 😁

**Comment by joaochris** [comment]
randomly
https://user-images.githubusercontent.com/76891864/228588670-55434683-ee76-4203-92b9-bdb814f29867.mp4
