### ISSUE TITLE
[FIX] Error importing an EPUB file [mwb_T]

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#26]
![image](https://user-images.githubusercontent.com/76891864/221416679-69d9fc81-7720-4b32-a95e-cd630ad7d1c6.png)

**Comment by rhahao** [comment]
Hi @joaochris, thanks for reporting this. I hope it is solved now.

**Comment by joaochris** [comment]
The same error still persists

**Comment by rhahao** [comment]
Probably, you are still being served by some old results. Have you already tried closing the app (or the browser) and try again?

**Comment by joaochris** [comment]
Yes!! The same error appears:
![image](https://user-images.githubusercontent.com/76891864/221431416-f47dbaa7-ce7d-4f30-82e5-726dec9b9b50.png)

**Comment by rhahao** [comment]
Mmh... so could you please check the Network tab in the Developer Tools, and filter it for Fetch/XHR only. There you should see 3 requests for docs-id. Could you please post here the result of these fetch?

**Comment by joaochris** [comment]
Does not appear these requests only announcement-v2

**Comment by rhahao** [comment]
Please try to import the source from jw.org first.

**Comment by joaochris** [comment]
But this error appears when I try to import an EPUB file. Is the option to import from JW.Org related? 😅

**Comment by rhahao** [comment]
lol... really sorry! I thought you are meaning the jw.org import. So is EPUB now available for your language? The code currently does not support importing EPUB for T language.

**Comment by joaochris** [comment]
No, from JW.ORG it works perfectly 😁

EPUB files were discontinued in 2023 so from 2022 onwards they are available.

I need this function to populate all the previous years parts to create the assignment history.

**Comment by rhahao** [comment]
Now I understand. 😁 I will look at it again.

**Comment by joaochris** [comment]
Thanks!

**Comment by rhahao** [comment]
Hi @joaochris, hope that it is good now 😊.
