### ISSUE TITLE
[FIX] Bug when unchecking an assignment. (Happens with some names)

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#314]
![CPE](https://github.com/sws2apps/cpe-sws/assets/76891864/85683106-7211-4334-b392-00602047d4b9)

**Comment by rhahao** [comment]
Hi @joaochris, thanks for reporting. I will have a look at it.

**Comment by rhahao** [comment]
@joaochris: I am not yet able to duplicate the issue so far. 😁But I will continue trying. Meanwhile, if you notice something related to the issue, please share.

**Comment by joaochris** [comment]
Hey @rhahao 
I zoomed out of the page and managed to uncheck after many times. It's strange because it doesn't happen every time, and only with some names.

**Comment by rhahao** [comment]
Hello @joaochris, really strange... at least your issue is now solved then. 😉
