### ISSUE TITLE
[FIX] Text does not appear [Spiritual Gems]

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#32]
![image](https://user-images.githubusercontent.com/76891864/221558078-4e72a490-be79-4f2f-80fc-967e03bf398d.png)

**Comment by rhahao** [comment]
🥴 oops... thanks @joaochris. I will prepare a fix for it asap. Currently, I am gradually working as well on the E2E tests for the app that should prevent this from happening. Until then, your feedback is really appreciated.
