### ISSUE TITLE
[Enhancement Idea] Improve assignment history

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#38]
In my opinion, I think that instead of a scrollbar, a dropdown menu would be better when designing (no scrollbar). A drop-down menu, which, when clicking on a name, would designate the person. No need for an "_Assign_" button.
It would make selecting a person easier. And then the history could appear in another form, perhaps on the side of the dropdown menu. Or in a separate place just for that, but that would be easily accessible, close to the designation pencil.

In all designations other than student designations:

It would be great if instead of displaying what is currently there, it showed the history of just that designation I selected.

For example, I clicked the edit pencil in the **President** field.

Then the history of all the brothers that were used as "**President**". From oldest to newest.

Example: Name | Last appointment (**President**)
Carlos Teixeira 
Josephus 11/01/2022 
Irenaeus 12/12/2022 
Socrates 12/26/2022 

Those that have not yet been used in this part may appear undated.

In its current form, I need to click on the name to show when a certain person was last used as "President".

With respect to a person's complete designation history, there could be an option that if clicked, this would appear (instead of clicking on the person's name).

========================================================== 

For student parts:
A filter that would show assignments made by a person from oldest to newest.
After implementing the filter to show only siblings or brothers, it will be better too.

Filter:
Name | Last used as Student                                                      | Last used as Assistant       
Maria | 21/10/2022 - Initial call (Main hall)                                 | 15/05/2022 - Initial call (Main hall)  
Peter | 30/01/2023 - Bible reading (Auxiliary Classroom 1)        | 20/01/2023 - Return visit  (Main hall)  

***If it is a Bible reading, show the last time a brother was used for a reading.
***If it is a talk, the last ones used for talk will appear.

NOTE: Currently I see that when we click the pencil on a certain part to designate, a designation history appears below, which I think is not necessary. It could be replaced by those suggestions I mentioned. One for all parts except student parts. And another one for student parties.

I understand that implementing this can be quite tricky, but these are just suggestions. What do you think?

**Comment by joaochris** [comment]
![image](https://user-images.githubusercontent.com/76891864/221895648-d2bee221-334e-49d4-ad82-44f00ad03666.png)

Thank you!

It would be more or less like this.

In {part} would be a variable that would show the part I clicked on, for example if I clicked on the pencil in the president field, it would show that in the name.

And [full history], when clicked would show all of that person's assignments.

This for all parts except student parts :)

**Comment by rhahao** [comment]
Ok, thanks! I will look at it and I will come back to you when it is ready.

**Comment by joaochris** [comment]
Hey @rhahao . I edited the text and removed some things that in my test are unnecessary in my suggestion.

**Comment by joaochris** [comment]
Hey @rhahao 
How much time!
How are things?
What about the progress of this and other suggestions I gave?

**Comment by rhahao** [comment]
Hello @joaochris. 😄 Very sorry for the time it take to finish this. Unfortunately, I’m not sure yet when it will be finished. I have very busy weeks lately, with some other theocratic works, and also adding Secretary features to CPE, which were requested urgently by some users. But let’s hope this should be handled within 2 or 3 weeks. Thanks!

**Comment by rhahao** [comment]
Hello @joaochris, please find below the preview of changes I have been working on to implement this suggestion:

This is what the selector will look like, for parts other than students in Field Ministry parts:
![image](https://github.com/sws2apps/cpe-sws/assets/26148770/41955063-3603-40dc-936d-0afa1e671cf3)

For the Field Ministry parts:
![image](https://github.com/sws2apps/cpe-sws/assets/26148770/8e5ea874-0750-44d3-8fa2-edbb147334da)

The last assignment will refer to when a person is assigned to that specific assignment.

For the full history, including the assistant history, the user need to click the new list icon.
![image](https://github.com/sws2apps/cpe-sws/assets/26148770/7fc99cdb-9547-42e5-a355-70a74d7a86e4)
![image](https://github.com/sws2apps/cpe-sws/assets/26148770/6171fbfc-fd22-4df6-895f-1b9924017442)

I hope it should be released on production very soon. 😊

**Comment by joaochris** [comment]
Hey! @rhahao 

I just tested it a little bit, and I really like what you added, showing if the person was already assigned in the meeting.

But in our case, where we activated the option for the chairman to be used for the opening prayer, can you remove that message? Also, can you also remove the opening prayer from the history?

Why?
As the chairman gives the opening prayer, it's as if the two things are intertwined.

![image](https://github.com/sws2apps/cpe-sws/assets/76891864/2fc31087-ba19-4794-9059-b6a845d8fbb5)
![image](https://github.com/sws2apps/cpe-sws/assets/76891864/eaa8c188-f8b0-4579-9fd4-438026ae1ccb)

Another thing... Would it be possible to let the selector titles follow the scroll bar? That is, the title remains displayed while using the scroll bar. I think it would be interesting.
![image](https://github.com/sws2apps/cpe-sws/assets/76891864/fefc6304-4b34-4d36-95aa-d063f752c6ec)

And about auto-fill, I really liked it!

Would it be possible to link elders to parts of elders in auto-fill?

Example: Local Needs
and parts that in the text have "to be done by an elder".

**Comment by rhahao** [comment]
ooops... I really forget that details. I will prepare a fix for this as soon as possible.

For the selector header, I had struggle customizing this component for that 😅, but I will take a time to think about another approach for it again.

**Comment by joaochris** [comment]
Hey! @rhahao 😄

Are you finished with the changes?
maybe you misunderstood? 😅

This message still appears.
![image](https://github.com/sws2apps/cpe-sws/assets/76891864/fb4bf72d-79e7-4295-964e-e5a32a867ebf)

And the history opening prayer still remains.
![image](https://github.com/sws2apps/cpe-sws/assets/76891864/1bc1117f-cf1b-407e-9b5d-ddd60bb88f6b)

**Comment by rhahao** [comment]
Hi @joaochris, yes, it will only affect new assignment for now. For the schedules that were already assigned, the history and this alert are still shown. But I will prepare an additional action to clean up the ones that were already assigned,

**Comment by joaochris** [comment]
Hey @rhahao 
Sorry for commenting on this closed topic.

But, I was in doubt.

Did it work to implement the history in the parts of elders? (In this case, to my understanding, would it be necessary to specify whether the person is a ministerial servant or an elder in the person registration?)

So you would be able to configure the history on local needs or parts that contain the phrase "to be done by an elder" to show only the elders. This would also cater for auto-completion (would only assign elders to those parts)

It is possible?

**Comment by rhahao** [comment]
Hello @joaochris! No problem at all!

 But don’t worry! I am still working on CPE to detect the elders part. Currently, the congregation needs to have a secretary user account in order to edit the person’s spiritual status. Therefore, CPE will now check if at least if you have one elder in the persons records, and then enable the elder filter. If not, it will handle the part as usual and manual edit may still be needed.
