### ISSUE TITLE
[FEAT] Substitute speaker

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#552]
Hello @rhahao how are you?

Thank you for your excellent work on the new updates.

Related to the weekend meeting, I would like to make a suggestion.

In cases where an unforeseen event happens to the designated speaker from another congregation and he is unable to give the speech. It would be interesting to add a field to add a substitute speaker from the congregation itself. So he would make the speech with the speeches he has already given.

**Comment by rhahao** [comment]
Hello @joaochris, I am doing fine thanks! Hope the same for you too. 😄

Thanks for this nice suggestion! I will add it to the backlog list. Just to confirm:

> So he would make the speech with the speeches he has already given.

Does this means that the public talk coordinator will only select the substitute speaker and that person will select the talk he will deliver for that scenario?

Thanks!

**Comment by joaochris** [comment]
Thanks! That's right, just a field to add the name of the congregation's replacement speaker. :)

**Comment by rhahao** [comment]
Got it! 👍
