### ISSUE TITLE
[FIX] Blank page [PDF] S-140

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#58]
I noticed that when downloading the [S-140] schedule in PDF sometimes a blank sheet appears, and then the next week appears.

**Comment by rhahao** [comment]
Hi @joaochris, thanks for reporting. Does this happen randomly as you said, or there is a specific schedule where it always behaves like that?

**Comment by joaochris** [comment]
:). Yes! randomly.

**Comment by rhahao** [comment]
Ok thanks! I will try to replicate that if I will be able to. 🤣

**Comment by joaochris** [comment]
Were you able to reproduce this one? Or does this just happen to me? HAHAHAHA

![image](https://user-images.githubusercontent.com/76891864/228263416-3bb8f3ff-4451-49e9-b407-ea9b6827d330.png)
Unfortunately this is random, is the problem in the pdf generator? If you displayed the error in the console, maybe it would be easier to discover the problem?

**Comment by rhahao** [comment]
Yes, I’ve been able to reproduce it as well. At some point, the content of the page reaches the bottom margin, that’s why it pushes it to a new page. It could be just a blank page, or like the one you posted above. 😁 For now, the solution would be to play with the spaces between each row to allow more content to fit in one page.

**Comment by joaochris** [comment]
![image](https://user-images.githubusercontent.com/76891864/228280778-2adc3b39-d3e7-4c58-bc24-7acde156d4d8.png)
In 5 weeks, if I define this number in the div before the last week, it's just right.

Wouldn't it be possible to create a pattern?

![image](https://user-images.githubusercontent.com/76891864/228281234-2840918a-0c72-4a4b-b5c4-a737d996aa4a.png)

The problem is that in the preview it looks like this, but in the pdf it is normal.
