### ISSUE TITLE
[FEAT] Chairman assigned automatically opening prayer and Organizational Accomplishments

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#6]
In congregations where the Chairman also does the opening prayer, it would be great if there was an option to enable auto-completion of the opening prayer when selecting the Chairman.

It could work just like the initial videos in the Apply Yourself To The Field Ministry section where nothing appears to fill. The Chairman is already designated automatically.

![Screenshot_16](https://user-images.githubusercontent.com/76891864/217399111-4704b435-11f7-4640-a4fa-49bbb177b657.png)

Also, he would not appear in the assignment history:
![Screenshot_12](https://user-images.githubusercontent.com/76891864/217389614-9c9bea57-eaed-4882-8e2a-7088a5862021.png)

**Comment by joaochris** [comment]
@rhahao How much time for this one?

**Comment by rhahao** [comment]
Hi @joaochris, now that the migration project was completed, it should be ready soon. (1 ~ 2 days). 😁

**Comment by rhahao** [comment]
Sure! Let’s hope that it still gets introduced until then. 😂😂
