### ISSUE TITLE
[FIX] Congregation Settings 

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#72]
![Screenshot_13](https://user-images.githubusercontent.com/76891864/224070004-137d467a-ac50-40dd-8ba1-7018d519809c.png)
![Screenshot_14](https://user-images.githubusercontent.com/76891864/224070039-04385906-84a4-4674-b889-45944f1b05ad.png)

**Comment by rhahao** [comment]
Hi @joaochris, thanks for reporting. I will check this, and hope to fix it asap.
