### ISSUE TITLE
PT-BR 2024

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#756]
Hi. Is the source material for PT-BR 2024 in progress? To import automatically

**Comment by rhahao** [comment]
Hello @joaochris, recently I switched from using WOL when getting source materials for your language. But for now, the latest data is not yet available on WOL. I'll think of another solution and will let you know if there is any update. Thanks.

**Comment by rhahao** [comment]
Hi @joaochris, this should be solved now. Thanks for your patience!

**Comment by joaochris** [comment]
Excellent, I just tested it and everything is fine. Thank you very much for the quick response. =]
