### ISSUE TITLE
[FIX] Error generate PDF S-89

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#770]
When I generate the PDF S-89 it loads infinitely, it doesn't show anything.

![IMG_20231213_204225.jpg](https://github.com/sws2apps/cpe-sws/assets/76891864/12a54a1c-62a2-4007-b2d3-0ee5b15052e5)

**Comment by rhahao** [comment]
Hi @joaochris. Thanks for the report. Could you please try to reselect the day for your midweek meeting in the Settings page, see if it solves it?

**Comment by joaochris** [comment]
Hi @rhahao. It worked when I changed it, but when I generated it from another month, it didn't work :D

**Comment by rhahao** [comment]
Interesting. Could you please try again reselecting it and send backup immediately after that. Then try to reload the app again if it solves it.
