### ISSUE TITLE
[FIX] Some words appear undefined and no designation appears

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#774]
Are those that do not show any words in the designations because of the changes from the 2024 meeting?

![IMG_20231213_204842.jpg](https://github.com/sws2apps/cpe-sws/assets/76891864/f01f3c63-2af8-4e68-b24a-937d033d1e25)

**Comment by rhahao** [comment]
Hi @joaochris, let me check.

**Comment by rhahao** [comment]
Hi @joaochris, may I please ask if you are able to check what assignment should appear in the undefined and those that are blanks? It will help to pinpoint where the issue is. Thanks in advance.

**Comment by joaochris** [comment]
I think I identified the problem. Now that I saw that the previous schedules were blank. The text is not appearing.

![image](https://github.com/sws2apps/cpe-sws/assets/76891864/3f371180-eac7-4ec5-a3f4-55224cf31979)

**Comment by rhahao** [comment]
Oh I see. Unfortunately, without an EPUB, we can no longer add these old schedules.

**Comment by joaochris** [comment]
But I had already downloaded the old schedules :D. Wasn't it supposed to be stored?

**Comment by rhahao** [comment]
True. It should be always there. Old schedules will only be deleted after 1 year. Not sure what happens that delete the sources on your side. :-)

**Comment by joaochris** [comment]
Oh no, I lost all the history :(. I believe it was in the update to 2024 as the meeting changed some parts. Why wouldn't I have to create a name match?

**Comment by rhahao** [comment]
So sorry to hear that! But still I am not really sure what was causing that behavior. I’ve tried and asked some users with old sources but all data were kept after the last update. 😔

**Comment by joaochris** [comment]
But before, the option to download old programs appeared. And now it doesn't appear. That could have been it :D

**Comment by joaochris** [comment]
Could I go back to older backups to try to rescue it and see if that was the case? Like after I downloaded the current schedules he modified the old ones.

**Comment by rhahao** [comment]
Yes, you can try restoring the backup. The backups are not stored like an history. Each time you send backup, it will do a merge and one backup will always be saved. This is the case also when you restore a backup. It will do a merge with your current local record. So, if the last backup saved still have those old schedules, you may have them restored.

**Comment by joaochris** [comment]
The problem is that the oldest backup is too recent. Can you restore older backups as an administrator?

**Comment by rhahao** [comment]
Unfortunately, no.

> The problem is that the oldest backup is too recent.

But here as I explained above, all your previous backup will not get lost if they were saved. If you send a new one, the old data and new data will be combined. So, if you cannot see them even if you restore the backup, probably these data were never backed up.

**Comment by joaochris** [comment]
Hi @rhahao. I filled it in manually and the names appeared :D. Is there a way to do this automatically?

**Comment by rhahao** [comment]
I will try to see if it will be possible to bring back the download old schedules feature. 😊

**Comment by rhahao** [comment]
@joaochris: You should be able to import all previous source materials now. Thank you.

**Comment by joaochris** [comment]
Hey! @rhahao 

Thank you. Thank you for making work simpler and easier. Immense gratitude.
