### ISSUE TITLE
[FEAT] PDF Weekend Meeting

### ISSUE THREAD

**Issue by joaochris** [sws2apps/cpe-sws#775]
Hello. I was testing the weekend meeting at CPE. Would it be possible to add text to identify the Substitute Speaker in the generated PDF? Because the name of the Speaker and Substitute appears in the same box.

**Comment by rhahao** [comment]
Hi @joaochris, thanks for this issue.

So far, CPE can assign the substitute speaker internally, and it appears only on the published schedules for those using CPE. It is not meant to appear in the schedule on the congregation board. I’ve checked on my side that is still what it does.

I am wondering what happened on your side causing the substitute speaker on the PDF. Could you help me on what steps should I do to reproduce the issue? Do you suggest also that this information should appear in the schedule for the congregation board?

**Comment by joaochris** [comment]
Hey @rhahao. Thx!

I thought it was supposed to appear hahaha

So I just filled in the replacement speaker and it showed up there when I generated the PDF below the main speaker.

I think it would be interesting to appear, considering that at the moment there are not all the elders in the CPE, so if it is in the PDF I could send it to them.

**Comment by rhahao** [comment]
For example this what I have:

![image](https://github.com/sws2apps/cpe-sws/assets/26148770/03a9c732-d68a-404d-a75b-ab8fbc5bd1ee)

This will export PDF like this:

![image](https://github.com/sws2apps/cpe-sws/assets/26148770/4067cf6c-ddea-46f6-be1e-631fa24a475f)

Two names will only appear if selecting person who is not yet approved to deliver 30 min talk, but only 15 min.

**Comment by rhahao** [comment]
> I think it would be interesting to appear, considering that at the moment there are not all the elders in the CPE, so if it is in the PDF I could send it to them.

I will keep this in mind when updating the weekend meeting template to a new one.
